version: '3.8'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  java_app:
    container_name: java_app
    image: 'pee-java-app:1.0.0'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    ports:
      - 8080:8002
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PWSD=postgres
    depends_on:
      - java_db